
name: test-actions

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: install deps
        working-directory: ./src/deta-express-starter
        run: npm ci
        shell: bash
      - name: Run build command
        working-directory: ./src/deta-express-starter
        run: npm run build
        shell: bash
      - id: scan
        uses: rohanshiva/actions@main
        with:
          app: "ffdbc447-c046-473f-be5c-0e1db34ebc09"
        env:
          DETA_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
